version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 7666
      MYSQL_DATABASE: csi_db
      MYSQL_USER: csi_user
      MYSQL_PASSWORD: 7666
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/csi_db_dump.sql:/docker-entrypoint-initdb.d/csi_db_dump.sql

  springboot:
    image: openjdk:17
    container_name: springboot
    depends_on:
      - mysql
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      sh -c "cd /app && ./mvnw clean package && java -jar target/your-app.jar"
    ports:
      - "8080:8080"

volumes:
  db_data:
